# Expects variable: ‘username’
# Expects variable: ‘location’
# Expects variable: ‘location-code’
# Expects variable: ‘pitometer-image’
# Expects variable: ‘subscription-id’
# Expects variable: ‘dynatrace-environment-id’
# Expects variable: ‘dynatrace-paas-token’
# Expects variable: ‘dynatrace-api-token’
# Expects variable: ‘dynatrace-base-url’

# disable the push trigger
trigger: none

variables:

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Delete
  displayName: Delete Azure resources
  jobs:  
  - job: Delete
    displayName: Delete
    pool:
      vmImage: $(vmImageName)
      
    steps:
    - task: AzureCLI@1
      displayName: 'Delete Demo Resources'
      inputs:
        azureSubscription: azure
        scriptPath: arm/remove.sh
        arguments: '"$(username)"'