# this pipeline is be run one-time as to setup the envionment
# this will just call arm/remove.sh
#
# Expects pipline variables: 
# azure-resource-prefix

# disable the push trigger
trigger: none

variables:

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Delete
  displayName: Delete Azure resources
  jobs:  
  - job: Delete
    displayName: Delete Azure resources
    pool:
      vmImage: $(vmImageName)
      
    steps:
    - task: AzureCLI@1
      displayName: 'Delete Demo Resources'
      inputs:
        azureSubscription: azure
        scriptPath: arm/remove.sh
        arguments: '"$(azure-resource-prefix)"'